name: Build & test

on: [push]

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install PHP
      uses: shivammathur/setup-php@1.3.7
      with:
        php-version: 7.4
    - name: Debug PHP and Composer
      run: |
        php --version
        php -m
        composer --version
    - name: Composer Install dependencies
      run: |
        composer install --prefer-dist --no-suggest
    - name: Composer Test
      run: |
        composer run-script test
  npm:
    name: NPM test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: NPM Clean install dependencies
        run: npm ci
      - name: NPM JSHint
        run: npm run lint
      - name: NPM Build
        run: npm run build
